#ifndef CONSTANTS_H
#define CONSTANTS_H

// General
#define FIRST_INSTALL "FIRSTINSTALL"
#define DEBUG_MODE "DEBUG"
#define CLEAR_SCRIPT_FILE "stlcompiler.sys"
#define SCAD_OUTPUT_FILE "outputscript.scad"
#define HOME_TAB 0
#define MENU1_TAB 1
#define MENU2_TAB 2
#define MENU3_TAB 3
#define SETTINGS_TAB 4
#define VISUALIZE_STL_TAB 5
#define OUTPUT_SCAD_TAB 6
#define APP_NAME "appname"
#define APP_VERSION "appversion"
#define TARGET_STRING "OpenSCAD_Model"
#define OUTPUT_STRING "OFC3DKEY"
#define DISLOCKPRO_TEMPLATE "qt_dislockpro_template_qt"
#define PROTEC_TEMPLATE "qt_protect_template_qt"
#define ABUSPLUS_TEMPLATE "qt_abusplus_template_qt"
#define AXI_TEMPLATE "qt_axi_template_qt"
#define VIERGE_TEMPLATE "qt_787svierge_qt"
#define OUTPUT_DIR "FFC41D0V"
#define TEMPLATES_DIR "templates"
#define OPENSCAD_DIR "STLCompiler"
#define OPENSCAD_EXE "stlcompiler.exe"
#define BLOCK_UID "uid"
#define BLOCK_SELECTED "selected"
#define BLOCK_CLOSED "closed"
#define NUMBER_OF_PINS "number_of_pins"
#define NUMBER_OF_LEVERS "number_of_levers"
#define NUMBER_OF_DISCS "number_of_discs"
#define ANSWER "answer"
#define DATA_DIR "data"
#define KEYBUILDER_DIR "keybuilder"
#define LAST_VISITED_DIR "lastdir"
#define GENERATE_STL_TEXT "Generate STL"
#define CANCEL_GENERATION_TEXT "Cancel Generation"
#define ENCODED_SCRIPT_NAME "_get_m2.dat"
#define IGNORED_OPENSCAD_ERROR "Could not initialize localization"
#define STL_BUILD_SUCCESS_MSG "STL BUILD SUCCESS"
#define STL_BUILD_FAILURE_MSG "STL BUILD FAILURE"
#define SOFTWARE_NOT_LICENSED_MSG "THIS SOFTWARE IS NOT LICENSED FOR THAT MACHINE"
#define BUILDING_STL_MSG "BUILDI_NG STL..."
#define USE_QT "_use_qt"
#define SETTINGS_KEY "SETTINGS"
#define ERASE_VALUE "0"
#define TEXT_LINE "TEXT LINE"

// Tags
#define TAG_ROOT "ROOT"
#define TAG_GROUP "group"
#define TAG_BLOCK "block"
#define TAG_KEY "key"
#define TAG_PARAMETER "parameter"
#define TAG_VARIABLES "variables"
#define TAG_VARIABLE "variable"
#define TAG_ITEM "item"

// Properties
#define PROPERTY_NAME "name"
#define PROPERTY_ORDER "order"
#define PROPERTY_VARIABLE "variable"
#define PROPERTY_SET_VARIABLE "set_variable"
#define PROPERTY_STL_VARIABLE "stl_variable"
#define PROPERTY_DXF_VARIABLE "dxf_variable"
#define PROPERTY_UI "ui"
#define PROPERTY_FILE_EXTENSION "extension"
#define PROPERTY_VALUE "value"
#define PROPERTY_LABELS "labels"
#define PROPERTY_VALUES "values"
#define PROPERTY_TYPE "type"
#define PROPERTY_INT "int"
#define PROPERTY_DOUBLE "double"
#define PROPERTY_STRING "string"
#define PROPERTY_BOOLEAN "boolean"
#define PROPERTY_MIRROR "mirror"
#define PROPERTY_TABLE "table"
#define PROPERTY_COLUMN_LABELS "columnlabels"
#define PROPERTY_COLUMN_VARIABLES "columnvariables"
#define PROPERTY_TARGET_ROW "targetrow"
#define PROPERTY_NROWS "nrows"
#define PROPERTY_TARGET_VARIABLE "targetvariable"
#define PROPERTY_USER_VALUE "userValue"
#define PROPERTY_VARIABLE_METHOD "variablemethod"
#define PROPERTY_VARIABLE_METHOD1 "method1"
#define PROPERTY_VARIABLE_METHOD2 "method2"
#define PROPERTY_ENABLED "enabled"
#define PROPERTY_DEFAULT "default"
#define PROPERTY_UNSET "ifunsetuse"
#define PROPERTY_EXCLUSIVE "exclusive"
#define PROPERTY_AUTO "auto"
#define PROPERTY_MIN_VALUE "minvalue"
#define PROPERTY_MAX_VALUE "maxvalue"
#define PROPERTY_CURRENT_ROW "currentrow"
#define PROPERTY_KEY_PREVIEW_IMAGE "keypreviewimage"
#define PROPERTY_ALWAYS_OPENED "alwaysopened"
#define PROPERTY_CAN_CLEAR "canclear"
#define PROPERTY_REFERENCE "reference"

// Widgets
#define WIDGET_LINE_EDIT "lineedit"
#define WIDGET_LINE_EDIT_RETURN "lineeditvalidateonreturn"
#define WIDGET_FILE_PICKER "filepicker"
#define WIDGET_EXCLUSIVE_CHOICE "exclusivechoice"
#define WIDGET_GENERIC_PARAMETER_TABLE "genericparametertable"
#define WIDGET_DOUBLE_TRIPLET "double_triplet"
#define WIDGET_YES_NO "yesno"
#define WIDGET_XYZMIRROR "xyzmirror"
#define VARIABLE_TYPE_OF_KEY "qt_type_of_key_qt"

// Values
#define VALUE_TRUE "true"
#define VALUE_FALSE "false"
#define VALUE_YES "YES"
#define VALUE_NO "NO"
#define VALUE_DEFAULT_VALUE "0"
#define VALUE_DEFAULT_TRIPLET_VALUE "[0,0,0]"

// Actions
#define ACTION_SET_NUMBER_OF_ROWS "setnumberofrows"

#endif // CONSTANTS_H
